url: habitus-unified.github.io

# Site settings
title: Habitus Unified
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Louise Heide Åkerman
  pic: 1
  position: CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/louise-heide-%C3%A5kerman-lalocalu/
    - title: github
      url: https://github.com/Louise-h-aa
    - title: envelope
      url: mailto:louiseheideaakerman@gmail.com 

- name: Siddharth Dushantha
  pic: 2
  position: CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/siddharth-dushantha/
    - title: github
      url: https://github.com/sdushantha
    - title: envelope
      url: mailto:siddharth.dushantha@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
